apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smartbank-production

bases:
  - ../../base

configMapGenerator:
  - name: smartbank-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
